// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddPost implements POST /add operation.
//
// Add two numbers.
//
// POST /add
func (UnimplementedHandler) AddPost(ctx context.Context, req *AddPostReq) (r AddPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DividePost implements POST /divide operation.
//
// Divide two numbers.
//
// POST /divide
func (UnimplementedHandler) DividePost(ctx context.Context, req *DividePostReq) (r DividePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MultiplyPost implements POST /multiply operation.
//
// Multiply two numbers.
//
// POST /multiply
func (UnimplementedHandler) MultiplyPost(ctx context.Context, req *MultiplyPostReq) (r MultiplyPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubtractPost implements POST /subtract operation.
//
// Subtract two numbers.
//
// POST /subtract
func (UnimplementedHandler) SubtractPost(ctx context.Context, req *SubtractPostReq) (r SubtractPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SumPost implements POST /sum operation.
//
// Add all numbers in an array.
//
// POST /sum
func (UnimplementedHandler) SumPost(ctx context.Context, req []float64) (r SumPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
