// Code generated by ogen, DO NOT EDIT.
package api

type AddPostRes interface {
	addPostRes()
}

type DividePostRes interface {
	dividePostRes()
}

type MultiplyPostRes interface {
	multiplyPostRes()
}

type SubtractPostRes interface {
	subtractPostRes()
}

type SumPostRes interface {
	sumPostRes()
}
