// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AddPostOperation      OperationName = "AddPost"
	DividePostOperation   OperationName = "DividePost"
	MultiplyPostOperation OperationName = "MultiplyPost"
	SubtractPostOperation OperationName = "SubtractPost"
	SumPostOperation      OperationName = "SumPost"
)
